### ISSUE TITLE
Add Application Insights Event Tracking

### ISSUE THREAD

**Issue by oliverspryn** [literal-life-church/live-streaming-api#25]
As a user, I need page view tracking so that I know how often my application is utilized.

**Acceptance Criteria:**
- GIVEN a running application
  - WHEN the locators page is viewed (regardless of a success or failure condition)
    - [x] THEN a page tracking event called `Locators` is logged to Application Insights
  - WHEN the status page is viewed (regardless of a success or failure condition)
    - [x] THEN a page tracking event called `Status` is logged to Application Insights
  - WHEN the start page is viewed (regardless of a success or failure condition)
    - [x] THEN a page tracking event called `Start` is logged to Application Insights
  - WHEN the stop page is viewed (regardless of a success or failure condition)
    - [x] THEN a page tracking event called `Stop` is logged to Application Insights
